server:
  port: 8081
spring:
  application:
    # 在注册中心的服务名
    name: hap-api
  cloud:
    nacos:
      discovery:
        # 启动的nacos的ip和端口
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hap
    driverClassName: com.mysql.cj.jdbc.Driver
oss:
  accessId: 1
  accessKey: 1
  bucket: oss-hap-test
  proxy: https://hap.heartape.com/oss-hap-test
  callbackHost: hap.heartape.com
token:
  secret: 1qweq2eq2wafawgf3
  header: hap-token