server:
  port: 8080
token:
  secret: 1qweq2eq2wafawgf3
  expireTime: 7
  header: hap-token
spring:
  application:
    # 在注册中心的服务名
    name: hap-gateway
  cloud:
    nacos:
      discovery:
        # 启动的nacos的ip和端口
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          # 开启从服务注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
      routes:
        - id: hap-api
          # uri路由到哪个地址,lb负载均衡
          uri: lb://hap-api
          # 断言,即条件判断,精确的路由放到前面
          predicates:
            - Path=/api/**
          # filters:
            # 重写路径
            # - RewritePath=/(?<segment>.*),/$\{segment}
        - id: hap-admin
          # uri路由到哪个地址,lb负载均衡
          uri: lb://hap-admin
          # 断言,即条件判断,精确的路由放到前面
          predicates:
            - Path=/admin/**
          # filters:
          # 重写路径
          # - RewritePath=/(?<segment>.*),/$\{segment}
#        - id: hap-business
#          # uri路由到哪个地址,lb负载均衡
#          uri: lb://hap-business
#          # 断言,即条件判断,精确的路由放到前面
#          predicates:
#            - Path=/business/**
#          # filters:
#          # 重写路径
#          # - RewritePath=/(?<segment>.*),/$\{segment}
